---
title: "STA9891 Final Project Jacky Luo"
output: html_notebook
---

```{r, warning=FALSE}
# rm(list = ls())
# cat("\014")
library(tidyverse)
library(glmnet)
library(randomForest)
require(dplyr)
library(pROC)
library(ROCR)

biodeg <- read_csv("./biodeg.csv")

biodeg <- biodeg[sample(nrow(biodeg)),]
names(biodeg) <- make.names(names(biodeg))
# transform the outcome to 0 or 1
biodeg <- biodeg %>% mutate(class = ifelse(class == "NRB",0,1))

# minus the predictor names & the outcome column
p = ncol(biodeg)-1
n = nrow(biodeg)-1

X = as.matrix(biodeg[1:nrow(biodeg) ,-ncol(biodeg)])
y = as.matrix(biodeg[1:nrow(biodeg) ,ncol(biodeg)])

set.seed(0)

n_train = ceiling(0.9*n)
n_test  = ceiling(n-n_train)

auc.train = matrix(0, 4, 50)  # empty matrix 4 models * 50 times for AUC
auc.test  = matrix(0, 4, 50)

for (trial_num in 1:50){
  cat("Trial number: ",trial_num,"\n")
  
  train.sub = sample(1:n)[1:n_train]
  X.train    =    X[train.sub, ]
  y.train    =    y[train.sub, ]
  X.test     =    X[-train.sub,]
  y.test     =    y[-train.sub,]
  
  ####################################################################################
  ####################################################################################
  # for AUC
  mod_num = 0
  alphas = c(0,0.5,1)
  for (a in alphas){

    if (a==1){ print("Fitting Lasso..."); mod_num = 1}
    if (a==0.5){ print("Fitting Elastic-Net..."); mod_num = 2}
    if (a==0){ print("Fitting Ridge..."); mod_num = 3}
    
    if (trial_num!=50){    
      fit     =  cv.glmnet(X.train, y.train, family = "binomial", alpha = a, 
                    nfolds = 10, type.measure = "auc")
    }
    # the only time that prints CV curve
    if (trial_num==50){
      # 3.c
      start_time <- Sys.time()
      fit     =  cv.glmnet(X.train, y.train, family = "binomial", alpha = a, 
                    nfolds = 10, type.measure = "auc")
      end_time <- Sys.time()
      cat("This is the 50th time! The 10-fold CV curve is: ", "\n")
      plot(fit)
      cat("To cross-validate the model: ", "\n")
      print(end_time - start_time)
    }
 
    fit       =  glmnet(X.train, y.train, family = "binomial", alpha = a, 
                        lambda = fit$lambda.min )
    beta0.hat      =  fit$a0
    beta.hat       =  as.vector(fit$beta)
    prob.train     =  exp(X.train %*% beta.hat + beta0.hat)/(1 + exp(X.train %*% beta.hat +  beta0.hat  ))
    prob.test      =  exp(X.test %*% beta.hat +  beta0.hat  )/(1 + exp(X.test %*% beta.hat +  beta0.hat  ))
    dt                      =        0.01
    thta                    =        1-seq(0,1, by=dt)
    thta.length             =        length(thta)
    FPR.train               =        matrix(0, thta.length)
    TPR.train               =        matrix(0, thta.length)
    FPR.test                =        matrix(0, thta.length)
    TPR.test                =        matrix(0, thta.length)
    
    for (i in c(1:thta.length)){
      y.hat.train             =        ifelse(prob.train > thta[i], 1, 0)
      FP.train                =        sum(y.train[y.hat.train==1] == 0)
      TP.train                =        sum(y.hat.train[y.train==1] == 1)
      P.train                 =        sum(y.train==1) # total positives in the data
      N.train                 =        sum(y.train==0) # total negatives in the data
      FPR.train[i]            =        FP.train/N.train # false positive rate
      TPR.train[i]            =        TP.train/P.train # true positive rate
      
      # calculate the FPR and TPR for test data 
      y.hat.test              =        ifelse(prob.test > thta[i], 1, 0)
      FP.test                 =        sum(y.test[y.hat.test==1] == 0) # false positives
      TP.test                 =        sum(y.hat.test[y.test==1] == 1) # true positives
      P.test                  =        sum(y.test==1) # total positives in the data
      N.test                  =        sum(y.test==0) # total negatives in the data
      FPR.test[i]             =        FP.test/N.test # false positive rate
      TPR.test[i]             =        TP.test/P.test # true positive rate
    }
    auc.train[mod_num, trial_num]     =       sum((TPR.train[1:(thta.length-1)] + 0.5 * diff(TPR.train)) * diff(FPR.train))
    auc.test[mod_num, trial_num]      =       sum((TPR.test[1:(thta.length-1)] + 0.5 * diff(TPR.test)) * diff(FPR.test))
    
    print("--------------------------------------------------------------------------------")
  }

  cat("Fitting random forest...", "\n")
  rf         =    randomForest(y.train ~ ., 
                       data = X.train, mtry = sqrt(p)) ## change mtry to 4 to speed up
  #the train AUC for rf
  rf_p_train <- predict(rf, newdata = X.train)
  roc.train <- roc(y.train, rf_p_train)
  auc.train[4,trial_num] = auc(roc.train)
  
  #the test AUC for rf
  rf_p_test <- predict(rf, newdata = X.test)
  roc.test <- roc(y.test, rf_p_test)
  auc.test[4,trial_num] = auc(roc.test)

  print("--------------------------------------------------------------------------------")

  ####################################################################################
  ####################################################################################
}


# 3.b Boxplot of the 50 AUCs (train and test) for n_train = 0.9n
par(mfrow=c(1,2))
boxplot(auc.train[1,], auc.train[2,], auc.train[3,], auc.train[4,],
        col = rainbow(3, s = 0.5), main = "AUC Boxplot for Training Set",
        names = c("lasso", "e_net", "ridge", "rf"))
boxplot(auc.test[1,], auc.test[2,], auc.test[3,], auc.test[4,],
        col = rainbow(3, s = 0.5), main = "AUC Boxplot for Test Set",
        names = c("lasso", "e_net", "ridge", "rf"))
```

```{r, warning=FALSE}
# create the table for AUC and time for all data
table  = matrix(0, 4, 2)
colnames(table) <- c('AUCs','Time to fit (s)')
rownames(table) <- c('Lasso','Elastic-Net','Ridge', 'Random Forest')

for (a in alphas){
    print("--------------------------------------------------------------------------------")
    cat("For all the data...", "\n")

    if (a==1){ print("Fitting Lasso..."); mod_num = 1}
    if (a==0.5){ print("Fitting Elastic-Net..."); mod_num = 2}
    if (a==0){ print("Fitting Ridge..."); mod_num = 3}
  
    
    start_time <- Sys.time()
    fit   =  cv.glmnet(X, y, family = "binomial", alpha = a, 
                    nfolds = 10, type.measure = "auc")
    end_time <- Sys.time()
    cat("Time for cross-validation: ", "\n")
    print(end_time - start_time)

    
    start_time <- Sys.time()
    fit   =  glmnet(X, y, family = "binomial", alpha = a, 
                        lambda = fit$lambda.min )
    end_time <- Sys.time()
    cat("To fit the model: ", "\n")
    print(end_time - start_time)
    table[mod_num, 2] = end_time - start_time
    
    beta0.hat      =  fit$a0
    beta.hat       =  as.vector(fit$beta)
    prob.test      =  exp(X.test %*% beta.hat +  beta0.hat  )/(1 + exp(X.test %*% beta.hat +  beta0.hat  ))
    dt                      =        0.01
    thta                    =        1-seq(0,1, by=dt)
    thta.length             =        length(thta)
    FPR.test                =        matrix(0, thta.length)
    TPR.test                =        matrix(0, thta.length)
    
    for (i in c(1:thta.length)){
      # calculate the FPR and TPR for test data 
      y.hat.test              =        ifelse(prob.test > thta[i], 1, 0)
      FP.test                 =        sum(y.test[y.hat.test==1] == 0) # false positives
      TP.test                 =        sum(y.hat.test[y.test==1] == 1) # true positives
      P.test                  =        sum(y.test==1) # total positives in the data
      N.test                  =        sum(y.test==0) # total negatives in the data
      FPR.test[i]             =        FP.test/N.test # false positive rate
      TPR.test[i]             =        TP.test/P.test # true positive rate
    }
    
    table[mod_num, 1]         =       sum((TPR.test[1:(thta.length-1)] + 0.5 * diff(TPR.test)) * diff(FPR.test))
    
    print("--------------------------------------------------------------------------------")
    
    s                         =     apply(X, 2, sd)
    if (a==1){beta.lasso      =     data.frame(c(1:p), as.vector(beta.hat) * s)
              colnames(beta.lasso)     =     c( "lasso_var", "value")}
    if (a==0.5){beta.enet     =     data.frame(c(1:p), as.vector(beta.hat) * s)
              colnames(beta.enet)      =     c( "enet_var", "value")}
    if (a==0){beta.ridge      =     data.frame(c(1:p), as.vector(beta.hat) * s)
              colnames(beta.ridge)     =     c( "ridge_var", "value")}
}

cat("Fitting random forest...", "\n")
start_time <- Sys.time()
rf    =    randomForest(y ~ ., 
                   data = X, mtry = sqrt(p)) ## change mtry to 4 to speed up
end_time <- Sys.time()
cat("To fit the model: ", "\n")
print(end_time - start_time)

table[4, 2] = end_time - start_time

#the test AUC for rf
rf_p_test <- predict(rf, newdata = X.test)
roc.test <- roc(y.test, rf_p_test)
table[4,1] = auc(roc.test)
table

print("--------------------------------------------------------------------------------")
var_importance            =     data.frame(c(1:p), as.vector(importance(rf)))
colnames(var_importance)  =     c( "rf_var", "importance")
    
# order the predictors
beta.lasso$lasso_var     =  factor(beta.lasso$lasso_var, levels = beta.enet$enet_var[order(beta.enet$value, decreasing = TRUE)])

beta.enet$enet_var       =  factor(beta.enet$enet_var, levels = 
beta.enet$enet_var[order(beta.enet$value, decreasing = TRUE)])

beta.ridge$ridge_var     =  factor(beta.ridge$ridge_var, levels = beta.enet$enet_var[order(beta.enet$value, decreasing = TRUE)])

var_importance$rf_var    =  factor(var_importance$rf_var, levels =
beta.enet$enet_var[order(beta.enet$value, decreasing = TRUE)])


library(ggplot2)
library(grid)
library(gridExtra)

lsPlot =  ggplot(beta.lasso, aes(x=lasso_var, y=value)) +
  geom_bar(stat = "identity", fill="white", colour="blue")

enPlot =  ggplot(beta.enet, aes(x=enet_var, y=value)) +
  geom_bar(stat = "identity", fill="white", colour="red")

rgPlot =  ggplot(beta.ridge, aes(x=ridge_var, y=value)) +
  geom_bar(stat = "identity", fill="white", colour="green")

rfPlot =  ggplot(var_importance, aes(x=rf_var, y=importance)) +
  geom_bar(stat = "identity", fill="white", colour="black")

lsPlot = lsPlot + 
  scale_x_discrete(breaks = beta.lasso$lasso_var[seq(1,length(beta.lasso$lasso_var),by=3)])
enPlot = enPlot + scale_x_discrete(breaks = beta.enet$enet_var[seq(1,length(beta.enet$enet_var),by=3)])
rgPlot = rgPlot + 
  scale_x_discrete(breaks = beta.ridge$ridge_var[seq(1,length(beta.ridge$ridge_var),by=3)])
rfPlot = rfPlot + 
  scale_x_discrete(breaks = var_importance$rf_var[seq(1,length(var_importance$rf_var),by=3)])

grid.arrange(enPlot, lsPlot, rgPlot, rfPlot, nrow = 4)

```
